name: Build Container Images as Anonymous
on:
  push:

jobs:
  build:
    strategy:
      matrix:
        component: [ 'mongo', 'postgres', 'debezium' ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Scripts
        run: shellcheck build-*.sh
      - name: Start local docker registry
        run: docker run -d -p 5500:5000 --restart=always --name registry registry:2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: |
            network=host
      - name: Run Scripts
        run: |
          ./build-all-multiplatform.sh ${matrix.component}
#          ./build-tool-images.sh latest
        env:
          DEBEZIUM_DOCKER_REGISTRY_PRIMARY_NAME: localhost:5500/debezium
          DEBEZIUM_DOCKER_REGISTRY_SECONDARY_NAME: localhost:5500/debeziumquay
